### PR TITLE
Update the build and project setup

### PR DESCRIPTION
**Pull request by ndelvalle**
This PR adds:

* [tsdx](https://github.com/jaredpalmer/tsdx) to test, lint and build the project (Setup everything basically)
* Update CI config to use `npm ci` instead of `npm install`
* Remove not used dependencies

Notes:
I started using tsdx just to build the project but I think is better to take full advantage of its capabilities (lint, hooks, test and build).
I removed a lot of config files to use the tsdx defaults, we can still tweak some things if we want to.

We need to investigate and fix a warning in the build and also for some reason the test folder gets compiled into the dist as well 🤦🏻‍♂️

Bundle sizes:
```
Bundle Size:  4.28 KB
Minified Size:  4.28 KB
Gzipped Size:  1.66 KB
```

@gillchristian @ianaya89 what are your thoughts on this library? I think is a magic black box, but makes our lives a lot easier 😇

This issue is related to https://github.com/Huemul/trae/issues/331

### CODE REVIEW

**Comment by gillchristian** [comment]
Looks good 😏

I pushed a fix to the warnings.

`tsconfig.json` use used by IDEs and tools (like TS lang server and jest) so everything needs to be included there. But during build we only want to include `./src` so I created a separate config file (`tsconfig.build.json`) for the build.

`tsconfig.json` also has `noEmit` set to `true` (ie. only type check), so we can run the compiler with that config to do type checking (`npm run ts:check`).

**Comment by gillchristian** [comment]
On thing I don't really like is how the `filesize` plugin "breaks" the output.

[asciicast](https://asciinema.org/a/312201)

**Comment by ndelvalle** [comment]
@gillchristian maybe we can use the filesize plugin only if we set a specific flag, it is not like we need that when we do normal changes.

**Comment by ndelvalle** [comment]
@gillchristian I'll create an issue to resolve the querystring warning on the build so we can keep iterating.

**Pull request merged**
