### PR TITLE
updated deps and resolve finally with a given config 

### PR DESCRIPTION
**Pull request by capaj**
why resolve with a config? To get at least some context to the finally handler as to which fetch request finished. 

Maybe we could add the url there as a second param?

### CODE REVIEW

**Comment by gillchristian** [comment]
Nice work @capaj, I like the idea.

**Comment by ndelvalle** [comment]
I like this @capaj 👍🏼. I Also like your suggestion of passing the formated url as second argument, because we don't have the base url in the config (In case they are using one). 
Can you remove the build bundle please? We should add that to the readme in the contribution section, sry about that.

**Comment by capaj** [comment]
@ndelvalle added the url as well, also edited readme.md

**Comment by ndelvalle** [comment]
Thanks @capaj I'll fix the lint warning that bithound is throwing, add a bit more to the README and publish a new version later today. Thanks again for the contribution 🙂

**Comment by capaj** [comment]
@ndelvalle could we get a new release? We're using it in production and we're using yarn. We need the latest changes deployed, so I tried using a url to my git repo. No, that does not work well with yarn, had to create this bug: https://github.com/yarnpkg/yarn/issues/2743

So then I tried publishing trae namespaced on `@capaj/trae` ahead of you. Guess what-that does work but it fails with flow-typed that we also use: https://github.com/flowtype/flow-typed/issues/671

So until you release, we have to hack it by including the minified trae file in our repo. Which sucks.

**Comment by gillchristian** [comment]
@capaj sorry for the inconvenience

I will publish the new version in a few minutes.

**Comment by gillchristian** [comment]
`trae 1.1.2 published` 🎉

@capaj

**Comment by capaj** [comment]
@gillchristian thx! you're da best

**Pull request merged**
