### PR TITLE
Create coverage directory before building

### PR DESCRIPTION
**Pull request by fvictorio**
Running `npm run build` after cloning the repo throws an error because the `coverage` directory does not exist. This PR creates the directory before running rollup.

### CODE REVIEW

**Comment by ndelvalle** [comment]
Nice catch @fvictorio but I think the right way to go here is to generate the [bundle-statistics](https://github.com/Huemul/trae/blob/master/build/rollup.js#L62) outside the coverage folder and add it to the `.gitignore`. I'm not sure why we add it there but it does not seem right to me. What do you think?

**Comment by gillchristian** [comment]
Maybe into `dist/statistics/...` ?

We still would have the same problem, whenever we run the build and the statistics directory is missing.

**Comment by ndelvalle** [comment]
Yeah makes sense is the stats of the dist after all. And I don't think we'll have a problem cause at that point the bundle was generated therefore the fist folder.

**Comment by fvictorio** [comment]
Updated.

**Comment by fvictorio** [comment]
Btw, the dist directory needs to be created because the stats seem to be generated before the build creates it.

**Pull request merged**
